name: dev_log_viewer
description: Real-time local log viewer for Flutter/Dart. Streams structured logs from your app to a searchable web UI on localhost.
version: 0.1.1
repository: https://github.com/ooluseye16/dev_log_viewer
issue_tracker: https://github.com/ooluseye16/dev_log_viewer/issues

topics:
  - logging
  - debug
  - developer-tools
  - cli

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^6.0.0

executables:
  dev_log_viewer: log_viewer
  dev_log_setup: setup
